### PR TITLE
Simplify build

### PR DESCRIPTION
**Pull request by csabapalfi**
Thought you might like a simpler build process for this repo.

Actually `npm run` is quite nice and you can replace grunt with it.

Totally understand if you want to keep grunt but I think it's just simpler without it.

### CODE REVIEW

**Comment by csabapalfi** [comment]
Ouch, looks like there're some differences in 'stock' jshint default config and the grunt-contrib version.

**Comment by csabapalfi** [comment]
Argh. Simpler but not working. Ignore me.

**Comment by mustela** [comment]
Hey @csabapalfi thanks for trying it! Will check `npm run` for sure! Thanks!

**Comment by lucasmpb** [comment]
Hi @csabapalfi, thanks for the tips!
I have removed grunt from the build process, and replace it with `npm run`. It looks much better now!

**Comment by csabapalfi** [comment]
Cool! 

Not sure why my build were failing when trying to merge but looks like you got it working now :)

**Pull request closed without merging**
